"""empty message

Revision ID: 1050fb9fff33
Revises: None
Create Date: 2015-07-31 09:00:48.853788

"""

# revision identifiers, used by Alembic.
revision = '1050fb9fff33'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
